name: it_venture_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  dio: ^4.0.6
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

assets:
    - assets/images/
    
fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf    

